// The `cloudflare:test` module declaration ships outside the package's main
// types entry, so pull it in explicitly for `yarn worker:tsc`. Its `env` is
// typed as the global `Cloudflare.Env` (normally generated by `wrangler
// types`), so augment that with the worker's real Env plus the test-only
// migrations binding.
/// <reference path="../../node_modules/@cloudflare/vitest-pool-workers/types/cloudflare-test.d.ts" />
import type { D1Migration } from "cloudflare:test";
import type { Env as WorkerEnv } from "../src/env";

// TEST_MIGRATIONS is optional: the agents SDK constrains its Env generic to
// Cloudflare.Env, and a required test-only binding would stop the worker's
// real Env from satisfying that constraint.
declare global {
	namespace Cloudflare {
		interface Env extends WorkerEnv {
			TEST_MIGRATIONS?: D1Migration[];
		}
	}
}

export {};
