/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsTabRouteImport } from './routes/settings/$tab'
import { Route as ChatChatIdRouteImport } from './routes/_chat.chat.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsTabRoute = SettingsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRouteRouteWithChildren
  '/': typeof ChatIndexRoute
  '/auth': typeof AuthRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/settings/': typeof SettingsIndexRoute
  '/chat/$id': typeof ChatChatIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/chat/$id': typeof ChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/settings': typeof SettingsRouteRouteWithChildren
  '/_chat': typeof ChatRouteWithChildren
  '/auth': typeof AuthRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/_chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_chat/chat/$id': typeof ChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/'
    | '/auth'
    | '/settings/$tab'
    | '/settings/'
    | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/settings/$tab' | '/' | '/settings' | '/chat/$id'
  id:
    | '__root__'
    | '/settings'
    | '/_chat'
    | '/auth'
    | '/settings/$tab'
    | '/_chat/'
    | '/settings/'
    | '/_chat/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/$tab': {
      id: '/settings/$tab'
      path: '/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof SettingsTabRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_chat/chat/$id': {
      id: '/_chat/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsTabRoute: typeof SettingsTabRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsTabRoute: SettingsTabRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatChatIdRoute: ChatChatIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
